# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c585de2293092a823bbcdcf254e009de61d9c1aa608ec11b8ee6f35c65c1f8798b608473401565abb8cdefc92754515f3770f12437b0fff8b1e051c7f1512ba0

test:
  secret_key_base: bdb4673bd0d4d4140dfc9288e728572102b5cb5aa977007a06ff160b953779f0e0bc9b352b4c030bb4ab3244e2133fe09a609aff0b3029f18df6d99169a7d5bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
